name: Tests

on: [ push, pull_request ]

jobs:
  test:
    name: Node v${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18, 20]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Update npm
        if: ${{ matrix.node-version == 14 }}
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        if: ${{ matrix.node-version > 14 }}
        run: npm run coverage

      - name: Run tests
        if: ${{ matrix.node-version == 14 }}
        run: npm run coverage -- -- -n--experimental-abortcontroller

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node-${{ matrix.node-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
